//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace BiztalkConfigLoader {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XMLSchema1.xsd", IsNullable=false)]
    public partial class Configuration {
        
        private HostType[] hostsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Host", IsNullable=false)]
        public HostType[] Hosts {
            get {
                return this.hostsField;
            }
            set {
                this.hostsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchema1.xsd")]
    public partial class HostType {
        
        private string nameField;
        
        private string ntgroupnameField;
        
        private bool isdefaultField;
        
        private bool trackingField;
        
        private bool authtrustedField;
        
        private string hosttypeField;
        
        private bool ishost32bitonlyField;
        
        private InstanceinfoType[] instanceinfoField;
        
        private HostTypeSettings settingsField;
        
        private HostTypeAdapter[] adaptersField;
        
        public HostType() {
            this.hosttypeField = "Inprocess";
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Ntgroupname {
            get {
                return this.ntgroupnameField;
            }
            set {
                this.ntgroupnameField = value;
            }
        }
        
        /// <remarks/>
        public bool Isdefault {
            get {
                return this.isdefaultField;
            }
            set {
                this.isdefaultField = value;
            }
        }
        
        /// <remarks/>
        public bool Tracking {
            get {
                return this.trackingField;
            }
            set {
                this.trackingField = value;
            }
        }
        
        /// <remarks/>
        public bool Authtrusted {
            get {
                return this.authtrustedField;
            }
            set {
                this.authtrustedField = value;
            }
        }
        
        /// <remarks/>
        public string Hosttype {
            get {
                return this.hosttypeField;
            }
            set {
                this.hosttypeField = value;
            }
        }
        
        /// <remarks/>
        public bool Ishost32bitonly {
            get {
                return this.ishost32bitonlyField;
            }
            set {
                this.ishost32bitonlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Instanceinfo")]
        public InstanceinfoType[] Instanceinfo {
            get {
                return this.instanceinfoField;
            }
            set {
                this.instanceinfoField = value;
            }
        }
        
        /// <remarks/>
        public HostTypeSettings Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Adapter", IsNullable=false)]
        public HostTypeAdapter[] Adapters {
            get {
                return this.adaptersField;
            }
            set {
                this.adaptersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/XMLSchema1.xsd")]
    public partial class InstanceinfoType {
        
        private string servernameField;
        
        private string usernameField;
        
        private string passwordField;
        
        private bool startInstanceField;
        
        /// <remarks/>
        public string servername {
            get {
                return this.servernameField;
            }
            set {
                this.servernameField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public bool StartInstance {
            get {
                return this.startInstanceField;
            }
            set {
                this.startInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
    public partial class HostTypeSettings {
        
        private uint subscriptionResumeAtField;
        
        private uint subscriptionPauseAtField;
        
        private uint messageDeliveryMaximumDelayField;
        
        private uint messageDeliveryOverdriveFactorField;
        
        private uint messagingMaxReceiveIntervalField;
        
        private string processMemoryThresholdField;
        
        private uint xlangMaxReceiveIntervalField;
        
        private uint throttlingTrackingDataMultiplierField;
        
        private uint inflightMessageThresholdField;
        
        /// <remarks/>
        public uint SubscriptionResumeAt {
            get {
                return this.subscriptionResumeAtField;
            }
            set {
                this.subscriptionResumeAtField = value;
            }
        }
        
        /// <remarks/>
        public uint SubscriptionPauseAt {
            get {
                return this.subscriptionPauseAtField;
            }
            set {
                this.subscriptionPauseAtField = value;
            }
        }
        
        /// <remarks/>
        public uint MessageDeliveryMaximumDelay {
            get {
                return this.messageDeliveryMaximumDelayField;
            }
            set {
                this.messageDeliveryMaximumDelayField = value;
            }
        }
        
        /// <remarks/>
        public uint MessageDeliveryOverdriveFactor {
            get {
                return this.messageDeliveryOverdriveFactorField;
            }
            set {
                this.messageDeliveryOverdriveFactorField = value;
            }
        }
        
        /// <remarks/>
        public uint MessagingMaxReceiveInterval {
            get {
                return this.messagingMaxReceiveIntervalField;
            }
            set {
                this.messagingMaxReceiveIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ProcessMemoryThreshold {
            get {
                return this.processMemoryThresholdField;
            }
            set {
                this.processMemoryThresholdField = value;
            }
        }
        
        /// <remarks/>
        public uint XlangMaxReceiveInterval {
            get {
                return this.xlangMaxReceiveIntervalField;
            }
            set {
                this.xlangMaxReceiveIntervalField = value;
            }
        }
        
        /// <remarks/>
        public uint ThrottlingTrackingDataMultiplier {
            get {
                return this.throttlingTrackingDataMultiplierField;
            }
            set {
                this.throttlingTrackingDataMultiplierField = value;
            }
        }
        
        /// <remarks/>
        public uint InflightMessageThreshold {
            get {
                return this.inflightMessageThresholdField;
            }
            set {
                this.inflightMessageThresholdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
    public partial class HostTypeAdapter {
        
        private string nameField;
        
        private HostTypeAdapterDirection directionField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public HostTypeAdapterDirection Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
    public enum HostTypeAdapterDirection {
        
        /// <remarks/>
        Send,
        
        /// <remarks/>
        Receive,
    }
}
